name: Setup CI environment for testing with sanitizers on Linux
description: Common part to tweak Linux CI runner environment for sanitizers
inputs:
  cc_name:
    description: C compiler name (for example, gcc-12)
    required: false
    default: clang-11
runs:
  using: composite
  steps:
    - name: Setup CI environment
      uses: ./.github/actions/setup
    - name: Set CMAKE_BUILD_PARALLEL_LEVEL
      run: |
        # Set CMAKE_BUILD_PARALLEL_LEVEL environment variable to
        # limit the number of parallel jobs for build/test step.
        NPROC=$(nproc)
        echo CMAKE_BUILD_PARALLEL_LEVEL=$(($NPROC + 1)) | tee -a $GITHUB_ENV
      shell: bash
    - name: Install build and test dependencies
      run: |
        apt -y update
        apt -y install ${CC_NAME} libstdc++-10-dev cmake ninja-build make perl
      shell: bash
      env:
        CC_NAME: ${{ inputs.cc_name }}
    - name: Set specific C compiler as a default toolchain
      run: |
        echo CC=${CC_NAME} | tee -a $GITHUB_ENV
      shell: bash
      env:
        CC_NAME: ${{ inputs.cc_name }}
