name: Sanitizers testing

on:
  push:
    branches-ignore:
      - '**-notest'
      - 'upstream-**'
    tags-ignore:
      - '**'

concurrency:
  # An update of a developer branch cancels the previously
  # scheduled workflow run for this branch. However, the default
  # branch, and long-term branch (tarantool/release/2.11,
  # tarantool/release/2.10, etc) workflow runs are never canceled.
  #
  # We use a trick here: define the concurrency group as 'workflow
  # run ID' + # 'workflow run attempt' because it is a unique
  # combination for any run. So it effectively discards grouping.
  #
  # XXX: we cannot use `github.sha` as a unique identifier because
  # pushing a tag may cancel a run that works on a branch push
  # event.
  group: ${{ startsWith(github.ref, 'refs/heads/tarantool/')
    && format('{0}-{1}', github.run_id, github.run_attempt)
    || format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  test-asan:
    strategy:
      fail-fast: false
      matrix:
        ARCH: [ARM64, x86_64]
        BUILDTYPE: [Debug, Release]
        OS: [Linux, macOS]
        # There are different top-level versions available for Linux and macOS runners.
        CC: [gcc-10, clang-11, gcc-15, clang-21]
        include:
          - BUILDTYPE: Debug
            CMAKEFLAGS: -DCMAKE_BUILD_TYPE=Debug -DLUA_USE_ASSERT=ON -DLUA_USE_APICHECK=ON
          - BUILDTYPE: Release
            CMAKEFLAGS: -DCMAKE_BUILD_TYPE=RelWithDebInfo
        exclude:
          # On current runners with Linux/ARM64 environment and
          # with LUAJIT_USE_SYSMALLOC=ON the system allocator returns addresses
          # with 48-bit set. Thus checkptrGC() fails with new Lua state pointer
          # and luajit fails to start with 'cannot create state: not enough memory'
          # error. So, we exclude these cases.
          - ARCH: ARM64
            OS: Linux
          # Exclude nonsuitable OS/compiler pairs.
          - OS: macOS
            CC: gcc-10
          - OS: macOS
            CC: clang-11
          - OS: Linux
            CC: gcc-15
          - OS: Linux
            CC: clang-21
          # Exclude macOS/ARM64/gcc case due to some tests are failed.
          # Details: https://github.com/tarantool/tarantool/issues/13018
          - ARCH: ARM64
            OS: macOS
            CC: gcc-15
    runs-on: [self-hosted, regular, '${{ matrix.OS }}', '${{ matrix.ARCH }}']
    name: >
      LuaJIT with ASan and UBSan (${{ matrix.OS }}/${{ matrix.ARCH }})
      ${{ matrix.BUILDTYPE }}
      CC:${{ matrix.CC }}
      GC64:ON SYSMALLOC:ON
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: setup Linux for sanitizers
        if: ${{ matrix.OS == 'Linux' }}
        uses: ./.github/actions/setup-sanitizers-linux
        with:
          cc_name: ${{ matrix.CC }}
      - name: setup macOS for sanitizers
        if: ${{ matrix.OS == 'macOS' }}
        uses: ./.github/actions/setup-sanitizers-macos
        with:
          cc_name: ${{ matrix.CC }}
      - name: configure
        # XXX: LuaJIT configuration requires a couple of tweaks:
        # LUAJIT_USE_SYSMALLOC=ON: Unfortunately, internal LuaJIT
        #   memory allocator is not instrumented yet, so to find
        #   any memory errors it's better to build LuaJIT with
        #   system provided memory allocator (i.e. run CMake
        #   configuration phase with -DLUAJIT_USE_SYSMALLOC=ON).
        #   For more info, see root CMakeLists.txt.
        # LUAJIT_ENABLE_GC64=ON: LUAJIT_USE_SYSMALLOC cannot be
        #   enabled on x64 without GC64, since realloc usually
        #   doesn't return addresses in the right address range.
        #   For more info, see root CMakeLists.txt.
        run: >
          cmake -S . -B ${{ env.BUILDDIR }}
          -G Ninja
          ${{ matrix.CMAKEFLAGS }}
          -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
          -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}
          -DLUAJIT_ENABLE_GC64=ON
          -DLUAJIT_USE_ASAN=ON
          -DLUAJIT_USE_SYSMALLOC=ON
          -DLUAJIT_USE_UBSAN=ON
      - name: Check for possible compiler misconfig
        working-directory: ${{ env.BUILDDIR }}
        env:
          CC_NAME: ${{ matrix.CC }}
        run: grep CMakeCache.txt -e CMAKE_C_COMPILER:STRING | grep ${CC_NAME}
      - name: build
        run: cmake --build . --parallel
        working-directory: ${{ env.BUILDDIR }}

      # Enable as much checks as possible. See more info here:
      # https://github.com/google/sanitizers/wiki/AddressSanitizerFlags,
      # https://github.com/google/sanitizers/wiki/SanitizerCommonFlags.
      - name: setup sanitizer options for Linux
        if: ${{ matrix.OS == 'Linux' }}
        env:
          ASAN_OPTIONS: "                    \
            detect_invalid_pointer_pairs=1:  \
            detect_leaks=1:                  \
            detect_stack_use_after_return=1: \
            dump_instruction_bytes=1:        \
            heap_profile=0:                  \
            print_suppressions=0:            \
            symbolize=1:                     \
            unmap_shadow_on_exit=1:          \
          "
          UBSAN_OPTIONS: "
            print_stacktrace=1 \
          "
        run: |
          echo ASAN_OPTIONS=${ASAN_OPTIONS} | tee -a $GITHUB_ENV
          echo UBSAN_OPTIONS=${UBSAN_OPTIONS} | tee -a $GITHUB_ENV
      - name: setup sanitizer options for macOS (common)
        if: ${{ matrix.OS == 'macOS' && matrix.ARCH != 'ARM64' && matrix.CC != 'clang-21' }}
        env:
          ASAN_OPTIONS: "                    \
            detect_invalid_pointer_pairs=1:  \
            detect_leaks=1:                  \
            detect_stack_use_after_return=1: \
            dump_instruction_bytes=1:        \
            heap_profile=0:                  \
            print_suppressions=0:            \
            symbolize=1:                     \
            unmap_shadow_on_exit=1:          \
          "
          UBSAN_OPTIONS: "
            print_stacktrace=1 \
          "
        run: |
          echo ASAN_OPTIONS=${ASAN_OPTIONS} | tee -a $GITHUB_ENV
          echo UBSAN_OPTIONS=${UBSAN_OPTIONS} | tee -a $GITHUB_ENV
      - name: setup sanitizer options for macOS (ARM64/clang-21)
        if: ${{ matrix.OS == 'macOS' && matrix.ARCH == 'ARM64' && matrix.CC == 'clang-21' }}
        # detect_leaks is disabled due to some tests build is failed.
        # Details: https://github.com/tarantool/tarantool/issues/13019
        env:
          ASAN_OPTIONS: "                    \
            detect_invalid_pointer_pairs=1:  \
            detect_leaks=0:                  \
            detect_stack_use_after_return=1: \
            dump_instruction_bytes=1:        \
            heap_profile=0:                  \
            print_suppressions=0:            \
            symbolize=1:                     \
            unmap_shadow_on_exit=1:          \
          "
          UBSAN_OPTIONS: "
            print_stacktrace=1 \
          "
        run: |
          echo ASAN_OPTIONS=${ASAN_OPTIONS} | tee -a $GITHUB_ENV
          echo UBSAN_OPTIONS=${UBSAN_OPTIONS} | tee -a $GITHUB_ENV
      - name: test
        run: cmake --build . --parallel --target LuaJIT-test
        working-directory: ${{ env.BUILDDIR }}
